#!/usr/bin/env bash
# bagwiz-install.sh - Install the bagwiz launcher AND its shell completion in one
# step. Invoked by `pixi run install` (see pixi.toml); not meant to be run on its
# own, because installing completion runs the built binary, which only works
# inside the activated pixi environment.
#
# It installs two things:
#   1. A `bagwiz` launcher on your PATH (default ~/.local/bin/bagwiz). bagwiz's
#      binary is built inside a pixi-managed ROS 2 environment and resolves its
#      ROS libraries and message schemas through that environment at run time, so
#      the bare binary cannot go on PATH. The launcher is a thin shim that hands
#      off to scripts/bagwiz-run.sh, which runs the per-distro binary from a
#      cached activation snapshot.
#   2. Tab completion for your current shell, via `bagwiz complete <shell>
#      --install`.
#
# Unlike a one-off manual install, `pixi run install` ALWAYS overwrites: an
# existing launcher and an existing completion file are replaced without asking,
# so re-running it after a rebuild simply refreshes both.
#
# Configuration (environment variables, since this runs as a pixi task):
#   BAGWIZ_INSTALL_DIR   Directory for the launcher. Default: ~/.local/bin.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

# Default install directory. ~/.local/bin is on PATH for most distributions'
# default login shells and needs no root privileges.
BAGWIZ_INSTALL_DIR="${BAGWIZ_INSTALL_DIR:-${HOME}/.local/bin}"

# Which built distro the launcher targets, and where its binary lives. The build
# task writes install/$PIXI_ENVIRONMENT_NAME, so default the launcher to that
# same env for a consistent build-then-install flow.
BAGWIZ_LAUNCH_DISTRO="${PIXI_ENVIRONMENT_NAME:-humble}"

# The distro is interpolated into the generated launcher and indexes the binary
# path; reject anything with shell metacharacters so a stray quote or '$' cannot
# corrupt it (mirrors the guard in scripts/bagwiz-run.sh).
if [[ ! ${BAGWIZ_LAUNCH_DISTRO} =~ ^[A-Za-z0-9._-]+$ ]]; then
    echo "[install] Invalid distro '${BAGWIZ_LAUNCH_DISTRO}': use letters, digits, '.', '_', or '-'." >&2
    exit 1
fi

# The built binary, by explicit per-distro path (same path the `run` task uses).
# For the GPU build, target a *-cuda environment (e.g. `pixi run -e humble-cuda
# install`). `pixi run install` no longer builds: it
# wires the launcher to whatever build-core or build-full already produced here,
# so require that a binary exists and point at how to build one if it does not.
built_binary="${REPO_DIR}/install/${BAGWIZ_LAUNCH_DISTRO}/bagwiz/bin/bagwiz"
if [[ ! -x ${built_binary} ]]; then
    echo "[install] No build found for '${BAGWIZ_LAUNCH_DISTRO}' at" >&2
    echo "[install]   ${built_binary}" >&2
    echo "[install] Build it first: pixi run -e ${BAGWIZ_LAUNCH_DISTRO} build-core" >&2
    echo "[install]   (or build-full for the map/SLAM command group)" >&2
    exit 1
fi

# scripts/bagwiz-run.sh is the launcher runtime the installed shim points at.
runner="${SCRIPT_DIR}/bagwiz-run.sh"
if [[ ! -x ${runner} ]]; then
    echo "[install] Missing launcher runtime: ${runner}" >&2
    echo "[install] Re-checkout the repository; install needs scripts/bagwiz-run.sh." >&2
    exit 1
fi

# ---------------------------------------------------------------------------
# 1. Install the launcher (always overwriting any existing one).
# ---------------------------------------------------------------------------
# mkdir -p is idempotent, so re-installing into an existing directory is a no-op.
if [[ ! -d ${BAGWIZ_INSTALL_DIR} ]]; then
    echo "[install] Creating install directory ${BAGWIZ_INSTALL_DIR}"
    mkdir -p "${BAGWIZ_INSTALL_DIR}"
fi

dest="${BAGWIZ_INSTALL_DIR}/bagwiz"
echo "[install] Installing bagwiz launcher to ${dest} (distro: ${BAGWIZ_LAUNCH_DISTRO})"

# Shell-quote the runner path so a repo checkout path containing a space, '$',
# backtick, or quote still produces a launcher that execs the right file.
printf -v runner_q '%q' "${runner}"

# Write the launcher: a thin shim that records which default distro to use and
# hands off to scripts/bagwiz-run.sh.
cat >"${dest}" <<EOF
#!/usr/bin/env bash
# bagwiz launcher (generated by scripts/bagwiz-install.sh via 'pixi run install').
# Runs bagwiz from its pixi-managed ROS 2 environment via scripts/bagwiz-run.sh.
# Re-run "pixi run -e <distro> install" to switch to a different built distro.
exec env BAGWIZ_DEFAULT_DISTRO="${BAGWIZ_LAUNCH_DISTRO}" \\
    ${runner_q} "\$@"
EOF
chmod 0755 "${dest}"

# ---------------------------------------------------------------------------
# 2. Install tab completion for the current shell (always overwriting).
# ---------------------------------------------------------------------------
# The generated completion script invokes `bagwiz` on PATH, so it pairs with the
# launcher above. Pick the script matching the login shell; fall back to bash for
# anything unrecognized (the user can install others with
# `bagwiz complete <shell> --install`).
case "$(basename "${SHELL:-bash}")" in
zsh) completion_shell="zsh" ;;
fish) completion_shell="fish" ;;
bash) completion_shell="bash" ;;
*)
    completion_shell="bash"
    echo "[install] Unrecognized login shell; installing bash completion." >&2
    ;;
esac

echo "[install] Installing ${completion_shell} completion"
# --overwrite so a stale completion file from a previous version is replaced.
"${built_binary}" complete --shell "${completion_shell}" --install --overwrite

# ---------------------------------------------------------------------------
# 3. PATH hint: the launcher is only usable (and completion only fires) once its
#    directory is on PATH.
# ---------------------------------------------------------------------------
case ":${PATH}:" in
*":${BAGWIZ_INSTALL_DIR}:"*)
    echo "[install] ${BAGWIZ_INSTALL_DIR} is on your PATH; run 'bagwiz' from anywhere."
    ;;
*)
    # Suggest the startup file matching the current login shell.
    case "$(basename "${SHELL:-}")" in
    zsh) shell_rc="${HOME}/.zshrc" ;;
    bash) shell_rc="${HOME}/.bashrc" ;;
    *) shell_rc="your shell startup file" ;;
    esac
    echo "[install] Note: ${BAGWIZ_INSTALL_DIR} is NOT on your PATH, so 'bagwiz' will" >&2
    echo "[install]       not be found until you add it. To make it permanent, append" >&2
    echo "[install]       it to ${shell_rc}:" >&2
    echo "[install]           echo 'export PATH=\"${BAGWIZ_INSTALL_DIR}:\$PATH\"' >> ${shell_rc}" >&2
    echo "[install]       Then reload it (e.g. 'source ${shell_rc}') or open a new shell." >&2
    ;;
esac
