name: build

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  colcon:
    strategy:
      fail-fast: false
      matrix:
        distro: [humble, jazzy]
    runs-on: ubuntu-latest
    container:
      image: ros:${{ matrix.distro }}-ros-base
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src/bagcli

      - name: Install rosdep dependencies
        shell: bash
        run: |
          apt-get update
          rosdep update --rosdistro ${{ matrix.distro }}
          rosdep install --from-paths src --ignore-src -y --rosdistro ${{ matrix.distro }}

      - name: colcon build
        shell: bash
        run: |
          source /opt/ros/${{ matrix.distro }}/setup.bash
          colcon build \
            --event-handlers console_direct+ \
            --cmake-args -DCMAKE_BUILD_TYPE=Release

      - name: colcon test
        shell: bash
        run: |
          source /opt/ros/${{ matrix.distro }}/setup.bash
          source install/setup.bash
          colcon test --event-handlers console_direct+
          colcon test-result --verbose
